apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sysadmin-agents

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

commonLabels:
  app.kubernetes.io/name: sysadmin-agents
  app.kubernetes.io/part-of: sysadmin-agents
